version: '3.7'

services:

  redis:
    image: 'redis/redis-stack:latest'
    container_name: redis
    environment:
      REDIS_HOST: ${REDIS_HOST:-localhost}
      REDIS_PORT: ${REDIS_PORT:-6379}
    ports:
      - "${REDIS_PORT:-6379}:6379"

  postgres:
    image: 'postgres:16.0-alpine'
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  url-shortener:
    image: 'url-shortener:latest'
    container_name: url-shortener
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:


