CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'USER'
);

CREATE TABLE links (
    id UUID PRIMARY KEY,
    long_link VARCHAR(1000) NOT NULL,
    short_link VARCHAR(40) NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiration_time TIMESTAMP NOT NULL,
    statistics INT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE
);
